apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-svc
  labels:
    {{- include "todo-chatbot.frontendLabels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "todo-chatbot.frontendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}
      protocol: TCP
